[project]
name = "zh-tw-embedding-model-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.3.0",
    "numpy>=2.3.4",
    "openai>=2.6.1",
    "scikit-learn>=1.7.2",
]
